FROM openjdk:8-jdk-alpine
MAINTAINER Silvere DJAM <silvere.djam@gmail.com>
ADD target/vehicleseller-backend.jar vehicleseller-backend.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","vehicleseller-backend.jar"]